import { mkdtempSync, readFileSync } from "node:fs";
import { Buffer } from "node:buffer";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { Context } from "@flintloom/kernel";
import modelsPlugin, { type T2iProvider } from "@flintloom/models";
import toolsPlugin, { type ToolRegistry } from "@flintloom/tools";
import { createImageGenerateTool } from "../src/index.ts";

describe("image_generate tool", () => {
  it("writes generated bytes to workspace", async () => {
    const workspace = mkdtempSync(join(tmpdir(), "flintloom-img-"));
    const ctx = new Context();
    ctx.plugin(modelsPlugin);
    ctx.plugin(toolsPlugin);
    const models = ctx.require<import("@flintloom/models").ModelRegistry>("models");
    const t2i: T2iProvider = {
      async generate() {
        return { bytes: new Uint8Array([0x89, 0x50]), mimeType: "image/png" };
      },
    };
    models.registerT2i("fake", t2i);
    models.setDefault("t2i", "fake");
    const tools = ctx.require<ToolRegistry>("tools");
    tools.register(createImageGenerateTool(models));
    const out = await tools.execute(
      "image_generate",
      { prompt: "cat", path: "out/test.png" },
      { workspaceRoot: workspace, signal: new AbortController().signal, channel: "test" },
    );
    expect(JSON.parse(out)).toMatchObject({ ok: true, path: "out/test.png" });
    expect(Buffer.from(readFileSync(join(workspace, "out/test.png")))).toEqual(
      Buffer.from([0x89, 0x50]),
    );
  });
});
